name: indian_stocks_app
description: A modern Flutter app for tracking Indian stock prices with beautiful UI and charts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  
  # Charts
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^30.1.37
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.12
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Neumorphic & Material Design
  clay_containers: ^0.3.2
  glassmorphism: ^3.0.0
  glass_kit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
